name: 'clang-format check/commit action'
description: 'run clang-format on your code with the option to just check the formatting'
author: 'purduesigbots'
branding:
  icon: align-center
  color: yellow
inputs:
  check:
    description: 'Just check if the formatting is correct'
    type: boolean
    default: false
  style:
    description: 'Style passed to clang-format. reads .clang-format file in the repo by default. See clang-format docs for more'
    default: 'file'
  base:
    description: 'The base branch/commit to base the formatting off of'
    default: 'HEAD^'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ fromJSON('["", "--diff"]')[inputs.check == 'true'] }}
    - ${{ inputs.style }}
    - ${{ inputs.base }}
